services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retro_game_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  springboot-backend-app:
    image: 930964825207.dkr.ecr.eu-west-2.amazonaws.com/retro-app-backend:latest
    container_name: springboot_local
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/retro_game_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  postgres_data: